// Generated by CoffeeScript 2.7.0
(function() {
  var addTermsAndPrivacy, csvCache, documentNameRegex, fileErrorRegex, filenameRegex, findInputElement, getInputElementByVariableName, getSanitizedHostname, getSanitizedPathname, getUserPrivilege, handleIframeResize, handleSubmitClick, hideInterviewErrors, hslSetup, isInIframe, isInterviewErrorPage, isLoggedIn, isOnInterviewPage, isOnRunUrl, isValidInterviewUrl, missingEndIfErrorRegex, missingVariableNameErrorRegex, recordedClioResponses, select2Loaded, send_height_to_parent, setSelectAnswer, setupChangePasswordPage, setupDownloadDocumentsPage, setupForgotPasswordPage, setupInterviewTakerPage, setupInterviewsListPage, setupNavDropdowns, setupNavEmailLink, setupRegistrationPage, setupResetPasswordPage, setupSigninPage, setupUserProfilePage, translateFileError, translateInterviewPageErrors, validUrlRegex, xmlSyntaxErrorRegex;

  setupNavDropdowns = function() {
    return $('.subnavTrigger').on('click', function(evt) {
      evt.preventDefault();
      $('.hslSubnav').not($(this).next('.hslSubnav')).hide();
      return $(this).next('.hslSubnav').toggle();
    }).on('blur', function(evt) {
      return window.setTimeout(function() {
        return $(evt.currentTarget).next('.hslSubnav').hide();
      }, 500);
    });
  };

  getInputElementByVariableName = function(variableName) {
    var fieldId;
    fieldId = btoa(variableName).replace(/=/g, '');
    return $(`#${fieldId}, [data-saveas=\"${fieldId}\"] input`);
  };

  findInputElement = function(variableName, i = 0) {
    var inputElement;
    inputElement = getInputElementByVariableName(variableName);
    if (variableName.includes('[i]') && !inputElement.length) {
      variableName = variableName.replace('[i]', `[${i}]`);
      inputElement = getInputElementByVariableName(variableName);
    } else {
      if (i > 0) {
        return;
      }
    }
    return inputElement;
  };

  setSelectAnswer = function($element, answer) {
    var $selectContainer, $selection;
    $selectContainer = $element;
    while (($selection = $selectContainer.find('.select2-selection__rendered')) && $selection.length === 0) {
      $selectContainer = $selectContainer.next();
    }
    $selection.text(answer.text);
    return $element.val(JSON.stringify(answer));
  };

  recordedClioResponses = {};

  window.initializeAutocomplete = function(modelType, variableName) {
    var $inputElement, i, placeholder, results;
    if (typeof $.fn.select2 === 'undefined') {
      return window.setTimeout(() => {
        return window.initializeAutocomplete(modelType, variableName);
      }, 200);
    } else {
      recordedClioResponses[modelType] || (recordedClioResponses[modelType] = {});
      placeholder = "Select an option";
      i = 0;
      results = [];
      while (($inputElement = findInputElement(variableName, i)) && $inputElement.length) {
        $inputElement.on('change', (e) => {
          if (daShowIfInProcess) {
            return e.stopImmediatePropagation();
          }
        });
        $inputElement.select2({
          placeholder,
          width: '100%',
          ajax: {
            url: `/api/documate/v1/clio/${modelType}`,
            dataType: 'json',
            delay: 250,
            data: function(params) {
              return {
                q: params.term,
                autocomplete: true
              };
            },
            transport: async function(params, success) {
              var response, searchParam;
              searchParam = params.data.q;
              if (recordedClioResponses[modelType][searchParam]) {
                response = recordedClioResponses[modelType][searchParam];
              } else {
                response = (await $.ajax(params));
                recordedClioResponses[modelType][searchParam] = response;
              }
              return success(response);
            }
          }
        });
        $inputElement.on('select2:select', function(selection) {
          return setSelectAnswer($(this), {
            id: selection.params.data.id,
            text: selection.params.data.text
          });
        });
        if ($inputElement.val()) {
          setSelectAnswer($inputElement, JSON.parse($inputElement.val()));
        }
        results.push(i++);
      }
      return results;
    }
  };

  csvCache = {};

  window.initializeCsvAutocomplete = function(csvName, variableName) {
    var $inputElement, i, placeholder, results;
    if (typeof $.fn.select2 === 'undefined') {
      return window.setTimeout(() => {
        return window.initializeCsvAutocomplete(csvName, variableName);
      }, 200);
    } else {
      csvCache[csvName] || (csvCache[csvName] = {});
      $inputElement = getInputElementByVariableName(variableName);
      placeholder = "Select an option";
      i = 0;
      results = [];
      while (($inputElement = findInputElement(variableName, i)) && $inputElement.length) {
        $inputElement.on('change', (e) => {
          if (daShowIfInProcess) {
            return e.stopImmediatePropagation();
          }
        });
        $inputElement.select2({
          placeholder: placeholder,
          width: '100%',
          minimumInputLength: 1,
          ajax: {
            url: `/api/documate/v1/data-sources/csv/${csvName}`,
            dataType: 'json',
            delay: 250,
            processResults: function(data) {
              return {
                results: data
              };
            },
            data: function(params) {
              return {
                query: params.term
              };
            },
            transport: async function(params, success) {
              var response, searchParam;
              searchParam = params.data.query || "";
              if (csvCache[csvName][searchParam]) {
                response = csvCache[csvName][searchParam];
              } else {
                response = (await $.ajax(params));
                csvCache[csvName][searchParam] = response;
              }
              return success(response);
            }
          }
        });
        $inputElement.on('select2:select', function(selection) {
          return setSelectAnswer($(this), {
            id: selection.params.data.id,
            text: selection.params.data.text,
            name: csvName
          });
        });
        if ($inputElement.val()) {
          setSelectAnswer($inputElement, JSON.parse($inputElement.val()));
        }
        results.push(i++);
      }
      return results;
    }
  };

  select2Loaded = false;

  setupInterviewTakerPage = function() {
    if (!($('body.dabody.interview').length > 0 || isOnRunUrl())) {
      return;
    }
    if (!select2Loaded) {
      $('head').prepend(`<link href="https://d34mmrz2ojoc57.cloudfront.net/select2.min.css" rel="stylesheet" />
<script src="https://d34mmrz2ojoc57.cloudfront.net/select2.min.js"></script>`);
      return select2Loaded = true;
    }
  };

  setupChangePasswordPage = function() {
    if (!($('body.dabody.userchange-password').length > 0)) {
      return;
    }
    $('#damain h1').remove();
    $('#damain > .row > div').attr('class', 'userChangePasswordContainer');
    return $('.userChangePasswordContainer').before('<h1 class="userChangePasswordHeader"><span>Change Password</span></h1>');
  };

  setupUserProfilePage = function() {
    if (!($('body.dabody.userprofile').length > 0)) {
      return;
    }
    $('#damain h1').remove();
    $('#damain > .row > div').attr('class', 'userProfileContainer');
    return $('.userProfileContainer').before('<h1 class="userProfileHeader"><span>Profile</span></h1>');
  };

  setupInterviewsListPage = function() {
    if (!($('body.dabody.interviews').length > 0)) {
      return;
    }
    $('#damain > .row > div').attr('class', 'interviewsListPageContainer');
    // Add warning to delete for an interview
    $('.interviewsListPageContainer table tr td .btn-warning').click(function(e) {
      e.preventDefault();
      if (!confirm('Attention: Deleting this entry will delete the entire session and all data associated with it. Do you still want to delete?')) {
        return;
      }
      return window.location.href = this.href;
    });
    return $('tbody td a.label.label-warning').attr('class', 'icon-close removeInterviewIcon').text(' ');
  };

  setupResetPasswordPage = function() {
    if (!($('body.userreset-password').length > 0)) {
      return;
    }
    return $('#damain > .row > div').attr('class', 'resetPasswordFormContainer');
  };

  setupForgotPasswordPage = function() {
    if (!($('body.userforgot-password').length > 0)) {
      return;
    }
    return $('#damain > .row > div').attr('class', 'forgotPasswordFormContainer');
  };

  setupRegistrationPage = function() {
    if (!($('body.userregister').length > 0)) {
      return;
    }
    $('#damain h1:contains("Register")').text('Create Account');
    $('#damain > .row > div').attr('class', 'signupFormContainer').find('h1 + p').text('Create an account to get started.');
    $('#damain .form-actions button').text('Create Account');
    return addTermsAndPrivacy();
  };

  setupSigninPage = function() {
    var forgotPasswordHref, signupHref;
    if (!($('body.usersign-in').length > 0)) {
      return;
    }
    signupHref = $('#damain .da-form-group a:contains("Register")').attr('href');
    forgotPasswordHref = $('#damain .da-form-group a:contains("Forgot your Password")').attr('href');
    $('#damain > .row > div').attr('class', 'signinFormContainer');
    addTermsAndPrivacy();
    $('#damain .form-actions').append("<div class='forgotPasswordLinkContainer'><a href='" + forgotPasswordHref + "'>I forgot my password</a></div>");
    $('#damain .form-actions').append("<div class='createAccountLinkContainer'><span>New?</span> <a href='" + signupHref + "'>Create an account</a></div>");
    return $('.signinFormContainer > h1').after('<div class="signinSubText"><p>Sign in to your account.</p></div>');
  };

  addTermsAndPrivacy = function() {
    return $('#damain .form-actions').append('<div class="signupFooterText"><p>By clicking Create Account, you agree to our <a target="blank" rel="noopener noreferrer" href="https://www.gavel.io/terms">Terms of Service</a> and <a target="blank" rel="noopener noreferrer" href="https://www.gavel.io/privacy">Privacy Policy</a></p></div>');
  };

  translateInterviewPageErrors = function() {
    if (!isValidInterviewUrl()) {
      return;
    }
    if (isInterviewErrorPage()) {
      return translateFileError();
    }
  };

  send_height_to_parent = () => {
    var height;
    height = document.getElementsByTagName("html")[0].offsetHeight;
    return parent.postMessage({
      "height": height
    }, "*");
  };

  handleIframeResize = function() {
    return window.addEventListener("load", () => {
      var config, observer;
      send_height_to_parent();
      window.addEventListener("resize", send_height_to_parent);
      observer = new MutationObserver(send_height_to_parent);
      config = {
        attributes: true,
        childList: true,
        characterData: true,
        subtree: true
      };
      return observer.observe(window.document, config);
    });
  };

  handleSubmitClick = function() {
    var buttons;
    buttons = $('.form-actions .btn-da');
    return buttons.each(function(button) {
      return buttons[button].addEventListener("click", () => {
        return parent.postMessage({
          "submit": "submit"
        }, "*");
      });
    });
  };

  hideInterviewErrors = function() {
    return $('#damain > *').hide();
  };

  isInterviewErrorPage = function() {
    return 'pre'.length > 0 && ($('blockquote.blockquote').length > 0 || $('h1').text() === "Error");
  };

  isOnRunUrl = function() {
    return window.location.pathname && (window.location.pathname.indexOf('/run/playground') === 0 || window.location.pathname.indexOf('/start/playground') === 0 || window.location.pathname.indexOf('/bundles/') === 0);
  };

  isValidInterviewUrl = function() {
    return window.location.search && validUrlRegex().exec(window.location.search) || isOnRunUrl();
  };

  fileErrorRegex = function() {
    return /filename:(.*)$/ig;
  };

  missingVariableNameErrorRegex = function() {
    return /was a reference to a variable '(.*)?' that could not/ig;
  };

  documentNameRegex = function() {
    return /template file: (.*)?\n/ig;
  };

  xmlSyntaxErrorRegex = function() {
    return /(XMLSyntaxError)/ig;
  };

  missingEndIfErrorRegex = function() {
    return /(Unexpected end of template. Jinja)/ig;
  };

  filenameRegex = function() {
    return /Filename: (.*)/ig;
  };

  validUrlRegex = function() {
    return /[\?\&]i=/ig;
  };

  translateFileError = function() {
    var documentAttributesDiv, documentAttributesPre, documentName, documentNameMatches, errorText, fileErrors, filename, missingEndIfErrors, missingVariableErrors, xmlSyntaxErrors;
    errorText = $('blockquote.blockquote').length ? $('blockquote.blockquote').text() : $('#damain pre').first().text();
    fileErrors = fileErrorRegex().exec(errorText);
    missingVariableErrors = missingVariableNameErrorRegex().exec(errorText);
    xmlSyntaxErrors = xmlSyntaxErrorRegex().exec(errorText);
    missingEndIfErrors = missingEndIfErrorRegex().exec(errorText);
    if (fileErrors && fileErrors.length && matches.length === 2) {
      hideInterviewErrors();
      if (getUserPrivilege() === 'user') {
        $('blockquote.blockquote').text("Something went wrong. Please try again later.");
      } else {
        $('blockquote.blockquote').text('There was an error with the document <code>' + matches[1] + '</code>.  Please check the syntax and re-upload the document.');
      }
      return $('blockquote.blockquote').show();
    } else if (missingVariableErrors && missingVariableErrors.length && missingVariableErrors.length === 2) {
      hideInterviewErrors();
      documentAttributesPre = $('#damain pre').last().text();
      documentNameMatches = documentNameRegex().exec(documentAttributesPre);
      documentName = documentNameMatches && documentNameMatches.length && documentNameMatches[1] ? ', <code>' + documentNameMatches[1] + '</code>, ' : "";
      errorText = 'Your document' + documentName + 'includes a variable <code>' + missingVariableErrors[1] + '</code>, that is not captured as a question in your interview. Please create an interview question to capture this variable name before you proceed.';
      $('blockquote.blockquote').html(errorText);
      return $('blockquote.blockquote').show();
    } else if (xmlSyntaxErrors && xmlSyntaxErrors.length && xmlSyntaxErrors.length === 2) {
      hideInterviewErrors();
      documentAttributesDiv = $('#damain div.highlight').last().text();
      documentNameMatches = documentNameRegex().exec(documentAttributesDiv);
      documentName = documentNameMatches && documentNameMatches.length && documentNameMatches[1] ? ', <code>' + documentNameMatches[1] + '</code>' : "";
      errorText = 'There is an error in the syntax of your Word document' + documentName + '. Please check the formatting, make sure you are not using any <a target="_blank" href="https://docs.google.com/document/d/1RHmERTTL6h_yM3yrAbmu2mBIh9U_2qbZq8PTnCN_SGI/edit?usp=sharing">unauthorized variable names</a>, and re-upload your document.';
      $('blockquote.blockquote').html(errorText);
      return $('blockquote.blockquote').show();
    } else if (missingEndIfErrors && missingEndIfErrors.length && missingEndIfErrors.length === 2) {
      hideInterviewErrors();
      filename = filenameRegex().exec(errorText)[1];
      errorText = `Your document \"${filename}\" has a formatting error. You have a conditional clause that needs to be closed with an \"end if\" statement. Please fix the formatting in your document and reupload it. Or email us at help@gavel.io to have our customer support help you.`;
      $('#damain pre').first().html(errorText).css("white-space", "pre-wrap");
      $('#damain h1').show();
      return $('#damain pre').first().show();
    }
  };

  getUserPrivilege = function() {
    var isAdmin, isDeveloper, navbarLinks;
    navbarLinks = $('.navbar li.dropdown .dropdown-menu');
    isAdmin = navbarLinks.find('a[href$="/config"]').length > 0;
    isDeveloper = navbarLinks.find('a[href$="/playground"]').length > 0;
    if (isAdmin) {
      return 'admin';
    }
    if (isDeveloper) {
      return 'developer';
    }
    return 'user';
  };

  setupDownloadDocumentsPage = function() {
    var backButton, downloadAllButton, yesnoTrueButton;
    return;
    if ($('#question .alert.alert-success').length > 0) { //last page
      $('body').addClass('endOfInterview');
      $('#question .alert.alert-success').removeClass('alert').removeClass('alert-success').addClass('hslTheFollowingDocumentsText');
      yesnoTrueButton = $('.btn.btn-primary.btn-da[value="True"]');
      if (yesnoTrueButton.length > 0) {
        $('#question > div').addClass('attachmentsPageWithYesno');
        $('.page-header').addClass('attachmentsPageWithYesno');
      }
      $('#questionbackbutton').remove();
      $('#backToQuestion').text('< Back');
      backButton = $('#question > .form-actions').addClass('backButton').remove();
      $('.tabbable').last().after(backButton);
      // $('#question > .form-actions').remove()
      $('ul.nav-tabs + .tab-content').append($('<div/>', {
        'class': "downloadIcon",
        'html': '<span class="fas fa-arrow-alt-circle-down"></span>'
      }).click(function() {
        var href;
        href = $(this).siblings('.tab-pane').find('a').first().attr('href');
        if (href.indexOf('amazonaws') !== -1) {
          return window.open(href);
        } else {
          return window.open(window.location.protocol + '//' + window.location.host + href);
        }
      }));
      $('#accordionOne').prev().addClass('endOfDocuments');
      $('p:contains("The document is available in the following formats")').remove();
      downloadAllButton = $('#accordionTwo').clone();
      downloadAllButton.find('.btn.btn-primary').text('Download All as Zip');
      $('#accordionTwo').remove();
      return $('.endOfDocuments').after(downloadAllButton);
    }
  };

  isLoggedIn = function() {
    return $('.navbar.navbar-dark li.dropdown > a').text().indexOf('@') !== -1;
  };

  getSanitizedHostname = function() {
    var re, replace;
    replace = '\\.';
    re = new RegExp(replace, 'g');
    return window.location.hostname.replace(re, '_');
  };

  getSanitizedPathname = function() {
    var pathname, pathnameArray;
    pathname = window.location.pathname;
    if (pathname) {
      pathname = pathname.replace(/^\//, '');
    }
    pathnameArray = pathname.split('/');
    if (pathnameArray.length > 1) {
      return pathnameArray[0] + pathnameArray[1];
    } else {
      return pathnameArray[0];
    }
  };

  isInIframe = function() {
    var err;
    try {
      return window.self !== window.top;
    } catch (error) {
      err = error;
      return true;
    }
  };

  isOnInterviewPage = function() {
    return window.location.pathname === '/interview' || isOnRunUrl();
  };

  setupNavEmailLink = function() { //Sign In (when logged out)/Username (when logged in) link
    var emailDropdownText, email_element, usernameElement;
    email_element = $('.navbar.navbar-dark li.dropdown > a');
    usernameElement = $('#nav_username');
    if (isLoggedIn()) {
      emailDropdownText = email_element.text().split('@')[0];
    } else {
      $('.navUsernameContainer').removeClass('navUsernameContainer');
      emailDropdownText = 'Sign In';
      usernameElement.parents('a').removeClass('subnavTrigger').attr('href', '/user/sign-in');
      usernameElement.siblings('span').remove();
    }
    return usernameElement.text(emailDropdownText);
  };

  hslSetup = function() {
    var helpLink, logoUrl, navbar, userRole;
    if (isInIframe()) {
      handleIframeResize();
    }
    if (isInIframe()) {
      handleSubmitClick();
    }
    translateInterviewPageErrors();
    $('body').removeClass('pad-for-navbar').removeClass('da-pad-for-navbar');
    setupInterviewTakerPage();
    if ($('#hslNav').length > 0) {
      return;
    }
    logoUrl = window.DOCUMATE_LOGO_URL || 'https://s3-us-west-1.amazonaws.com/hsldocassemble/assets/hsl_logo.png';
    helpLink = window.location && window.location.hostname === 'docs.helpselflegal.com' ? '<li class="hslHelpLink"><a href="https://www.gavel.io/contact">Help</a></li>' : '';
    navbar = `<nav id="hslNav">
  <div class="hslNavContainer">

    <a href="/" class="logoContainer">
      <img src="${logoUrl}" class="hslNavLogoImage" />
    </a>

    <div class="linksContainer">

      <ul class="links">
        ${helpLink}
        <li>
          <a id="hslDashboardLink" class="hslDashboardLink" href="/playground">Dashboard</a>
        </li>
        <li>
          <a class="subnavTrigger navUsernameContainer" href="">
            <span id="nav_username">Me</span>&nbsp;<span class="fas fa-caret-down"></span>
          </a>
          <ul class="hslSubnav">
            <li class="hslTakenInterviewsLink">
              <a href="/dashboard">Workflows Taken</a>
            </li>
            <li>
              <a href="/user/profile">Account</a>
            </li>
            <li>
              <a href="/user/sign-out">Sign&nbsp;Out</a>
            </li>
          </ul>
          <a href=""></a>
        </li>
      </ul>

    </div>

  </div>
</nav>`;
    userRole = getUserPrivilege();
    $('body').addClass([getSanitizedPathname(), getSanitizedHostname()]);
    $('body.playground').prepend('<div id="hsl-em-root"></div>').removeClass('pad-for-navbar').removeClass('da-pad-for-navbar');
    $('body').prepend(navbar);
    setupNavEmailLink();
    setupRegistrationPage();
    setupSigninPage();
    setupForgotPasswordPage();
    setupResetPasswordPage();
    setupInterviewsListPage();
    setupUserProfilePage();
    setupChangePasswordPage();
    if (userRole === 'user') {
      $('#hslDashboardLink').remove();
    }
    if (userRole !== 'admin') {
      $('.playground .container#damain > .row').hide();
    }
    setupNavDropdowns();
    $('body.playground #damain > .row > .col-sm-8.col-md-8.col-lg-8').removeClass('col-sm-8 col-md-8 col-lg-8').addClass('col-sm-12 col-md-12 col-lg-12');
    $('body').css({
      visibility: 'visible'
    });
    return setupDownloadDocumentsPage();
  };

  if (!window.DOCUMATE_GLOBAL_JS_LOADED) {
    $(document).on('ready daPageLoad', hslSetup);
    hslSetup();
    window.DOCUMATE_GLOBAL_JS_LOADED = true;
  }

}).call(this);
/*
 * File: iframeResizer.contentWindow.js
 * Desc: Include this file in any page being loaded into an iframe
 *       to force the iframe to resize to the content size.
 * Requires: iframeResizer.js on host page.
 * Doc: https://github.com/davidjbradshaw/iframe-resizer
 * Author: David J. Bradshaw - dave@bradshaw.net
 *
 */

// eslint-disable-next-line sonarjs/cognitive-complexity, no-shadow-restricted-names
(function (undefined) {
  if (typeof window === "undefined") return; // don't run for server side render

  var autoResize = true,
    base = 10,
    bodyBackground = "",
    bodyMargin = 0,
    bodyMarginStr = "",
    bodyObserver = null,
    bodyPadding = "",
    calculateWidth = false,
    doubleEventList = { resize: 1, click: 1 },
    eventCancelTimer = 128,
    firstRun = true,
    height = 1,
    heightCalcModeDefault = "bodyOffset",
    heightCalcMode = heightCalcModeDefault,
    initLock = true,
    initMsg = "",
    inPageLinks = {},
    interval = 32,
    intervalTimer = null,
    logging = false,
    mouseEvents = false,
    msgID = "[iFrameSizer]", // Must match host page msg ID
    msgIdLen = msgID.length,
    myID = "",
    resetRequiredMethods = {
      max: 1,
      min: 1,
      bodyScroll: 1,
      documentElementScroll: 1,
    },
    resizeFrom = "child",
    sendPermit = true,
    target = window.parent,
    targetOriginDefault = "*",
    tolerance = 0,
    triggerLocked = false,
    triggerLockedTimer = null,
    throttledTimer = 16,
    width = 1,
    widthCalcModeDefault = "scroll",
    widthCalcMode = widthCalcModeDefault,
    win = window,
    onMessage = function () {
      warn("onMessage function not defined");
    },
    onReady = function () {},
    onPageInfo = function () {},
    customCalcMethods = {
      height: function () {
        warn("Custom height calculation function not defined");
        return document.documentElement.offsetHeight;
      },
      width: function () {
        warn("Custom width calculation function not defined");
        return document.body.scrollWidth;
      },
    },
    eventHandlersByName = {},
    passiveSupported = false;

  function noop() {}

  try {
    var options = Object.create(
      {},
      {
        passive: {
          get: function () {
            passiveSupported = true;
          },
        },
      }
    );
    window.addEventListener("test", noop, options);
    window.removeEventListener("test", noop, options);
  } catch (error) {
    /* */
  }

  function addEventListener(el, evt, func, options) {
    el.addEventListener(evt, func, passiveSupported ? options || {} : false);
  }

  function removeEventListener(el, evt, func) {
    el.removeEventListener(evt, func, false);
  }

  function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }

  // Based on underscore.js
  function throttle(func) {
    var context,
      args,
      result,
      timeout = null,
      previous = 0,
      later = function () {
        previous = Date.now();
        timeout = null;
        result = func.apply(context, args);
        if (!timeout) {
          // eslint-disable-next-line no-multi-assign
          context = args = null;
        }
      };

    return function () {
      var now = Date.now();

      if (!previous) {
        previous = now;
      }

      var remaining = throttledTimer - (now - previous);

      context = this;
      args = arguments;

      if (remaining <= 0 || remaining > throttledTimer) {
        if (timeout) {
          clearTimeout(timeout);
          timeout = null;
        }

        previous = now;
        result = func.apply(context, args);

        if (!timeout) {
          // eslint-disable-next-line no-multi-assign
          context = args = null;
        }
      } else if (!timeout) {
        timeout = setTimeout(later, remaining);
      }

      return result;
    };
  }

  function formatLogMsg(msg) {
    return msgID + "[" + myID + "] " + msg;
  }

  function log(msg) {
    if (logging && "object" === typeof window.console) {
      // eslint-disable-next-line no-console
      console.log(formatLogMsg(msg));
    }
  }

  function warn(msg) {
    if ("object" === typeof window.console) {
      // eslint-disable-next-line no-console
      console.warn(formatLogMsg(msg));
    }
  }

  function init() {
    readDataFromParent();
    log("Initialising iFrame (" + window.location.href + ")");
    readDataFromPage();
    setMargin();
    setBodyStyle("background", bodyBackground);
    setBodyStyle("padding", bodyPadding);
    injectClearFixIntoBodyElement();
    checkHeightMode();
    checkWidthMode();
    stopInfiniteResizingOfIFrame();
    setupPublicMethods();
    setupMouseEvents();
    startEventListeners();
    inPageLinks = setupInPageLinks();
    sendSize("init", "Init message from host page");
    onReady();
  }

  function readDataFromParent() {
    function strBool(str) {
      return "true" === str;
    }

    var data = initMsg.substr(msgIdLen).split(":");

    myID = data[0];
    bodyMargin = undefined !== data[1] ? Number(data[1]) : bodyMargin; // For V1 compatibility
    calculateWidth = undefined !== data[2] ? strBool(data[2]) : calculateWidth;
    logging = undefined !== data[3] ? strBool(data[3]) : logging;
    interval = undefined !== data[4] ? Number(data[4]) : interval;
    autoResize = undefined !== data[6] ? strBool(data[6]) : autoResize;
    bodyMarginStr = data[7];
    heightCalcMode = undefined !== data[8] ? data[8] : heightCalcMode;
    bodyBackground = data[9];
    bodyPadding = data[10];
    tolerance = undefined !== data[11] ? Number(data[11]) : tolerance;
    inPageLinks.enable = undefined !== data[12] ? strBool(data[12]) : false;
    resizeFrom = undefined !== data[13] ? data[13] : resizeFrom;
    widthCalcMode = undefined !== data[14] ? data[14] : widthCalcMode;
    mouseEvents = undefined !== data[15] ? Boolean(data[15]) : mouseEvents;
  }

  function depricate(key) {
    var splitName = key.split("Callback");

    if (splitName.length === 2) {
      var name =
        "on" + splitName[0].charAt(0).toUpperCase() + splitName[0].slice(1);
      this[name] = this[key];
      delete this[key];
      warn(
        "Deprecated: '" +
          key +
          "' has been renamed '" +
          name +
          "'. The old method will be removed in the next major version."
      );
    }
  }

  function readDataFromPage() {
    function readData() {
      var data = window.iFrameResizer;

      log("Reading data from page: " + JSON.stringify(data));
      Object.keys(data).forEach(depricate, data);

      onMessage = "onMessage" in data ? data.onMessage : onMessage;
      onReady = "onReady" in data ? data.onReady : onReady;
      targetOriginDefault =
        "targetOrigin" in data ? data.targetOrigin : targetOriginDefault;
      heightCalcMode =
        "heightCalculationMethod" in data
          ? data.heightCalculationMethod
          : heightCalcMode;
      widthCalcMode =
        "widthCalculationMethod" in data
          ? data.widthCalculationMethod
          : widthCalcMode;
    }

    function setupCustomCalcMethods(calcMode, calcFunc) {
      if ("function" === typeof calcMode) {
        log("Setup custom " + calcFunc + "CalcMethod");
        customCalcMethods[calcFunc] = calcMode;
        calcMode = "custom";
      }

      return calcMode;
    }

    if (
      "iFrameResizer" in window &&
      Object === window.iFrameResizer.constructor
    ) {
      readData();
      heightCalcMode = setupCustomCalcMethods(heightCalcMode, "height");
      widthCalcMode = setupCustomCalcMethods(widthCalcMode, "width");
    }

    log("TargetOrigin for parent set to: " + targetOriginDefault);
  }

  function chkCSS(attr, value) {
    if (-1 !== value.indexOf("-")) {
      warn("Negative CSS value ignored for " + attr);
      value = "";
    }
    return value;
  }

  function setBodyStyle(attr, value) {
    if (undefined !== value && "" !== value && "null" !== value) {
      document.body.style[attr] = value;
      log("Body " + attr + ' set to "' + value + '"');
    }
  }

  function setMargin() {
    // If called via V1 script, convert bodyMargin from int to str
    if (undefined === bodyMarginStr) {
      bodyMarginStr = bodyMargin + "px";
    }

    setBodyStyle("margin", chkCSS("margin", bodyMarginStr));
  }

  function stopInfiniteResizingOfIFrame() {
    document.documentElement.style.height = "";
    document.body.style.height = "";
    log('HTML & body height set to "auto"');
  }

  function manageTriggerEvent(options) {
    var listener = {
      add: function (eventName) {
        function handleEvent() {
          sendSize(options.eventName, options.eventType);
        }

        eventHandlersByName[eventName] = handleEvent;

        addEventListener(window, eventName, handleEvent, { passive: true });
      },
      remove: function (eventName) {
        var handleEvent = eventHandlersByName[eventName];
        delete eventHandlersByName[eventName];

        removeEventListener(window, eventName, handleEvent);
      },
    };

    if (options.eventNames && Array.prototype.map) {
      options.eventName = options.eventNames[0];
      options.eventNames.map(listener[options.method]);
    } else {
      listener[options.method](options.eventName);
    }

    log(
      capitalizeFirstLetter(options.method) +
        " event listener: " +
        options.eventType
    );
  }

  function manageEventListeners(method) {
    manageTriggerEvent({
      method: method,
      eventType: "Animation Start",
      eventNames: ["animationstart", "webkitAnimationStart"],
    });
    manageTriggerEvent({
      method: method,
      eventType: "Animation Iteration",
      eventNames: ["animationiteration", "webkitAnimationIteration"],
    });
    manageTriggerEvent({
      method: method,
      eventType: "Animation End",
      eventNames: ["animationend", "webkitAnimationEnd"],
    });
    manageTriggerEvent({
      method: method,
      eventType: "Input",
      eventName: "input",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Mouse Up",
      eventName: "mouseup",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Mouse Down",
      eventName: "mousedown",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Orientation Change",
      eventName: "orientationchange",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Print",
      eventName: ["afterprint", "beforeprint"],
    });
    manageTriggerEvent({
      method: method,
      eventType: "Ready State Change",
      eventName: "readystatechange",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Touch Start",
      eventName: "touchstart",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Touch End",
      eventName: "touchend",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Touch Cancel",
      eventName: "touchcancel",
    });
    manageTriggerEvent({
      method: method,
      eventType: "Transition Start",
      eventNames: [
        "transitionstart",
        "webkitTransitionStart",
        "MSTransitionStart",
        "oTransitionStart",
        "otransitionstart",
      ],
    });
    manageTriggerEvent({
      method: method,
      eventType: "Transition Iteration",
      eventNames: [
        "transitioniteration",
        "webkitTransitionIteration",
        "MSTransitionIteration",
        "oTransitionIteration",
        "otransitioniteration",
      ],
    });
    manageTriggerEvent({
      method: method,
      eventType: "Transition End",
      eventNames: [
        "transitionend",
        "webkitTransitionEnd",
        "MSTransitionEnd",
        "oTransitionEnd",
        "otransitionend",
      ],
    });
    if ("child" === resizeFrom) {
      manageTriggerEvent({
        method: method,
        eventType: "IFrame Resized",
        eventName: "resize",
      });
    }
  }

  function checkCalcMode(calcMode, calcModeDefault, modes, type) {
    if (calcModeDefault !== calcMode) {
      if (!(calcMode in modes)) {
        warn(
          calcMode + " is not a valid option for " + type + "CalculationMethod."
        );
        calcMode = calcModeDefault;
      }
      log(type + ' calculation method set to "' + calcMode + '"');
    }

    return calcMode;
  }

  function checkHeightMode() {
    heightCalcMode = checkCalcMode(
      heightCalcMode,
      heightCalcModeDefault,
      getHeight,
      "height"
    );
  }

  function checkWidthMode() {
    widthCalcMode = checkCalcMode(
      widthCalcMode,
      widthCalcModeDefault,
      getWidth,
      "width"
    );
  }

  function startEventListeners() {
    if (true === autoResize) {
      manageEventListeners("add");
      setupMutationObserver();
    } else {
      log("Auto Resize disabled");
    }
  }

  //   function stopMsgsToParent() {
  //     log('Disable outgoing messages')
  //     sendPermit = false
  //   }

  //   function removeMsgListener() {
  //     log('Remove event listener: Message')
  //     removeEventListener(window, 'message', receiver)
  //   }

  function disconnectMutationObserver() {
    if (null !== bodyObserver) {
      /* istanbul ignore next */ // Not testable in PhantonJS
      bodyObserver.disconnect();
    }
  }

  function stopEventListeners() {
    manageEventListeners("remove");
    disconnectMutationObserver();
    clearInterval(intervalTimer);
  }

  //   function teardown() {
  //     stopMsgsToParent()
  //     removeMsgListener()
  //     if (true === autoResize) stopEventListeners()
  //   }

  function injectClearFixIntoBodyElement() {
    var clearFix = document.createElement("div");
    clearFix.style.clear = "both";
    // Guard against the following having been globally redefined in CSS.
    clearFix.style.display = "block";
    clearFix.style.height = "0";
    document.body.appendChild(clearFix);
  }

  function setupInPageLinks() {
    function getPagePosition() {
      return {
        x:
          window.pageXOffset !== undefined
            ? window.pageXOffset
            : document.documentElement.scrollLeft,
        y:
          window.pageYOffset !== undefined
            ? window.pageYOffset
            : document.documentElement.scrollTop,
      };
    }

    function getElementPosition(el) {
      var elPosition = el.getBoundingClientRect(),
        pagePosition = getPagePosition();

      return {
        x: parseInt(elPosition.left, 10) + parseInt(pagePosition.x, 10),
        y: parseInt(elPosition.top, 10) + parseInt(pagePosition.y, 10),
      };
    }

    function findTarget(location) {
      function jumpToTarget(target) {
        var jumpPosition = getElementPosition(target);

        log(
          "Moving to in page link (#" +
            hash +
            ") at x: " +
            jumpPosition.x +
            " y: " +
            jumpPosition.y
        );
        sendMsg(jumpPosition.y, jumpPosition.x, "scrollToOffset"); // X&Y reversed at sendMsg uses height/width
      }

      var hash = location.split("#")[1] || location, // Remove # if present
        hashData = decodeURIComponent(hash),
        target =
          document.getElementById(hashData) ||
          document.getElementsByName(hashData)[0];

      if (undefined !== target) {
        jumpToTarget(target);
      } else {
        log(
          "In page link (#" +
            hash +
            ") not found in iFrame, so sending to parent"
        );
        sendMsg(0, 0, "inPageLink", "#" + hash);
      }
    }

    function checkLocationHash() {
      var hash = window.location.hash;
      var href = window.location.href;

      if ("" !== hash && "#" !== hash) {
        findTarget(href);
      }
    }

    function bindAnchors() {
      function setupLink(el) {
        function linkClicked(e) {
          e.preventDefault();

          /* jshint validthis:true */
          findTarget(this.getAttribute("href"));
        }

        if ("#" !== el.getAttribute("href")) {
          addEventListener(el, "click", linkClicked);
        }
      }

      Array.prototype.forEach.call(
        document.querySelectorAll('a[href^="#"]'),
        setupLink
      );
    }

    function bindLocationHash() {
      addEventListener(window, "hashchange", checkLocationHash);
    }

    function initCheck() {
      // Check if page loaded with location hash after init resize
      setTimeout(checkLocationHash, eventCancelTimer);
    }

    function enableInPageLinks() {
      /* istanbul ignore else */ // Not testable in phantonJS
      if (Array.prototype.forEach && document.querySelectorAll) {
        log("Setting up location.hash handlers");
        bindAnchors();
        bindLocationHash();
        initCheck();
      } else {
        warn(
          "In page linking not fully supported in this browser! (See README.md for IE8 workaround)"
        );
      }
    }

    if (inPageLinks.enable) {
      enableInPageLinks();
    } else {
      log("In page linking not enabled");
    }

    return {
      findTarget: findTarget,
    };
  }

  function setupMouseEvents() {
    if (mouseEvents !== true) return;

    function sendMouse(e) {
      sendMsg(0, 0, e.type, e.screenY + ":" + e.screenX);
    }

    function addMouseListener(evt, name) {
      log("Add event listener: " + name);
      addEventListener(window.document, evt, sendMouse);
    }

    addMouseListener("mouseenter", "Mouse Enter");
    addMouseListener("mouseleave", "Mouse Leave");
  }

  function setupPublicMethods() {
    log("Enable public methods");

    win.parentIFrame = {
      autoResize: function autoResizeF(resize) {
        if (true === resize && false === autoResize) {
          autoResize = true;
          startEventListeners();
        } else if (false === resize && true === autoResize) {
          autoResize = false;
          stopEventListeners();
        }
        sendMsg(0, 0, "autoResize", JSON.stringify(autoResize));
        return autoResize;
      },

      close: function closeF() {
        sendMsg(0, 0, "close");
        // teardown()
      },

      getId: function getIdF() {
        return myID;
      },

      getPageInfo: function getPageInfoF(callback) {
        if ("function" === typeof callback) {
          onPageInfo = callback;
          sendMsg(0, 0, "pageInfo");
        } else {
          onPageInfo = function () {};
          sendMsg(0, 0, "pageInfoStop");
        }
      },

      moveToAnchor: function moveToAnchorF(hash) {
        inPageLinks.findTarget(hash);
      },

      reset: function resetF() {
        resetIFrame("parentIFrame.reset");
      },

      scrollTo: function scrollToF(x, y) {
        sendMsg(y, x, "scrollTo"); // X&Y reversed at sendMsg uses height/width
      },

      scrollToOffset: function scrollToF(x, y) {
        sendMsg(y, x, "scrollToOffset"); // X&Y reversed at sendMsg uses height/width
      },

      sendMessage: function sendMessageF(msg, targetOrigin) {
        sendMsg(0, 0, "message", JSON.stringify(msg), targetOrigin);
      },

      setHeightCalculationMethod: function setHeightCalculationMethodF(
        heightCalculationMethod
      ) {
        heightCalcMode = heightCalculationMethod;
        checkHeightMode();
      },

      setWidthCalculationMethod: function setWidthCalculationMethodF(
        widthCalculationMethod
      ) {
        widthCalcMode = widthCalculationMethod;
        checkWidthMode();
      },

      setTargetOrigin: function setTargetOriginF(targetOrigin) {
        log("Set targetOrigin: " + targetOrigin);
        targetOriginDefault = targetOrigin;
      },

      size: function sizeF(customHeight, customWidth) {
        var valString =
          "" + (customHeight || "") + (customWidth ? "," + customWidth : "");
        sendSize(
          "size",
          "parentIFrame.size(" + valString + ")",
          customHeight,
          customWidth
        );
      },
    };
  }

  function initInterval() {
    if (0 !== interval) {
      log("setInterval: " + interval + "ms");
      intervalTimer = setInterval(function () {
        sendSize("interval", "setInterval: " + interval);
      }, Math.abs(interval));
    }
  }

  // Not testable in PhantomJS
  /* istanbul ignore next */
  function setupBodyMutationObserver() {
    function addImageLoadListners(mutation) {
      function addImageLoadListener(element) {
        if (false === element.complete) {
          log("Attach listeners to " + element.src);
          element.addEventListener("load", imageLoaded, false);
          element.addEventListener("error", imageError, false);
          elements.push(element);
        }
      }

      if (mutation.type === "attributes" && mutation.attributeName === "src") {
        addImageLoadListener(mutation.target);
      } else if (mutation.type === "childList") {
        Array.prototype.forEach.call(
          mutation.target.querySelectorAll("img"),
          addImageLoadListener
        );
      }
    }

    function removeFromArray(element) {
      elements.splice(elements.indexOf(element), 1);
    }

    function removeImageLoadListener(element) {
      log("Remove listeners from " + element.src);
      element.removeEventListener("load", imageLoaded, false);
      element.removeEventListener("error", imageError, false);
      removeFromArray(element);
    }

    function imageEventTriggered(event, type, typeDesc) {
      removeImageLoadListener(event.target);
      sendSize(type, typeDesc + ": " + event.target.src);
    }

    function imageLoaded(event) {
      imageEventTriggered(event, "imageLoad", "Image loaded");
    }

    function imageError(event) {
      imageEventTriggered(event, "imageLoadFailed", "Image load failed");
    }

    function mutationObserved(mutations) {
      sendSize(
        "mutationObserver",
        "mutationObserver: " + mutations[0].target + " " + mutations[0].type
      );

      // Deal with WebKit / Blink asyncing image loading when tags are injected into the page
      mutations.forEach(addImageLoadListners);
    }

    function createMutationObserver() {
      var target = document.querySelector("body"),
        config = {
          attributes: true,
          attributeOldValue: false,
          characterData: true,
          characterDataOldValue: false,
          childList: true,
          subtree: true,
        };

      observer = new MutationObserver(mutationObserved);

      log("Create body MutationObserver");
      observer.observe(target, config);

      return observer;
    }

    var elements = [],
      MutationObserver =
        window.MutationObserver || window.WebKitMutationObserver,
      observer = createMutationObserver();

    return {
      disconnect: function () {
        if ("disconnect" in observer) {
          log("Disconnect body MutationObserver");
          observer.disconnect();
          elements.forEach(removeImageLoadListener);
        }
      },
    };
  }

  function setupMutationObserver() {
    var forceIntervalTimer = 0 > interval;

    // Not testable in PhantomJS
    /* istanbul ignore if */ if (
      window.MutationObserver ||
      window.WebKitMutationObserver
    ) {
      if (forceIntervalTimer) {
        initInterval();
      } else {
        bodyObserver = setupBodyMutationObserver();
      }
    } else {
      log("MutationObserver not supported in this browser!");
      initInterval();
    }
  }

  // document.documentElement.offsetHeight is not reliable, so
  // we have to jump through hoops to get a better value.
  function getComputedStyle(prop, el) {
    var retVal = 0;
    el = el || document.body; // Not testable in phantonJS

    retVal = document.defaultView.getComputedStyle(el, null);
    retVal = null !== retVal ? retVal[prop] : 0;

    return parseInt(retVal, base);
  }

  function chkEventThottle(timer) {
    if (timer > throttledTimer / 2) {
      throttledTimer = 2 * timer;
      log("Event throttle increased to " + throttledTimer + "ms");
    }
  }

  // Idea from https://github.com/guardian/iframe-messenger
  function getMaxElement(side, elements) {
    var elementsLength = elements.length,
      elVal = 0,
      maxVal = 0,
      Side = capitalizeFirstLetter(side),
      timer = Date.now();

    for (var i = 0; i < elementsLength; i++) {
      elVal =
        elements[i].getBoundingClientRect()[side] +
        getComputedStyle("margin" + Side, elements[i]);
      if (elVal > maxVal) {
        maxVal = elVal;
      }
    }

    timer = Date.now() - timer;

    log("Parsed " + elementsLength + " HTML elements");
    log("Element position calculated in " + timer + "ms");

    chkEventThottle(timer);

    return maxVal;
  }

  function getAllMeasurements(dimensions) {
    return [
      dimensions.bodyOffset(),
      dimensions.bodyScroll(),
      dimensions.documentElementOffset(),
      dimensions.documentElementScroll(),
    ];
  }

  function getTaggedElements(side, tag) {
    function noTaggedElementsFound() {
      warn("No tagged elements (" + tag + ") found on page");
      return document.querySelectorAll("body *");
    }

    var elements = document.querySelectorAll("[" + tag + "]");

    if (elements.length === 0) noTaggedElementsFound();

    return getMaxElement(side, elements);
  }

  function getAllElements() {
    return document.querySelectorAll("body *");
  }

  var getHeight = {
      bodyOffset: function getBodyOffsetHeight() {
        return (
          document.body.offsetHeight +
          getComputedStyle("marginTop") +
          getComputedStyle("marginBottom")
        );
      },

      offset: function () {
        return getHeight.bodyOffset(); // Backwards compatability
      },

      bodyScroll: function getBodyScrollHeight() {
        return document.body.scrollHeight;
      },

      custom: function getCustomWidth() {
        return customCalcMethods.height();
      },

      documentElementOffset: function getDEOffsetHeight() {
        return document.documentElement.offsetHeight;
      },

      documentElementScroll: function getDEScrollHeight() {
        return document.documentElement.scrollHeight;
      },

      max: function getMaxHeight() {
        return Math.max.apply(null, getAllMeasurements(getHeight));
      },

      min: function getMinHeight() {
        return Math.min.apply(null, getAllMeasurements(getHeight));
      },

      grow: function growHeight() {
        return getHeight.max(); // Run max without the forced downsizing
      },

      lowestElement: function getBestHeight() {
        return Math.max(
          getHeight.bodyOffset() || getHeight.documentElementOffset(),
          getMaxElement("bottom", getAllElements())
        );
      },

      taggedElement: function getTaggedElementsHeight() {
        return getTaggedElements("bottom", "data-iframe-height");
      },
    },
    getWidth = {
      bodyScroll: function getBodyScrollWidth() {
        return document.body.scrollWidth;
      },

      bodyOffset: function getBodyOffsetWidth() {
        return document.body.offsetWidth;
      },

      custom: function getCustomWidth() {
        return customCalcMethods.width();
      },

      documentElementScroll: function getDEScrollWidth() {
        return document.documentElement.scrollWidth;
      },

      documentElementOffset: function getDEOffsetWidth() {
        return document.documentElement.offsetWidth;
      },

      scroll: function getMaxWidth() {
        return Math.max(
          getWidth.bodyScroll(),
          getWidth.documentElementScroll()
        );
      },

      max: function getMaxWidth() {
        return Math.max.apply(null, getAllMeasurements(getWidth));
      },

      min: function getMinWidth() {
        return Math.min.apply(null, getAllMeasurements(getWidth));
      },

      rightMostElement: function rightMostElement() {
        return getMaxElement("right", getAllElements());
      },

      taggedElement: function getTaggedElementsWidth() {
        return getTaggedElements("right", "data-iframe-width");
      },
    };

  function sizeIFrame(
    triggerEvent,
    triggerEventDesc,
    customHeight,
    customWidth
  ) {
    function resizeIFrame() {
      height = currentHeight;
      width = currentWidth;

      sendMsg(height, width, triggerEvent);
    }

    function isSizeChangeDetected() {
      function checkTolarance(a, b) {
        var retVal = Math.abs(a - b) <= tolerance;
        return !retVal;
      }

      currentHeight =
        undefined !== customHeight ? customHeight : getHeight[heightCalcMode]();
      currentWidth =
        undefined !== customWidth ? customWidth : getWidth[widthCalcMode]();

      return (
        checkTolarance(height, currentHeight) ||
        (calculateWidth && checkTolarance(width, currentWidth))
      );
    }

    function isForceResizableEvent() {
      return !(triggerEvent in { init: 1, interval: 1, size: 1 });
    }

    function isForceResizableCalcMode() {
      return (
        heightCalcMode in resetRequiredMethods ||
        (calculateWidth && widthCalcMode in resetRequiredMethods)
      );
    }

    function logIgnored() {
      log("No change in size detected");
    }

    function checkDownSizing() {
      if (isForceResizableEvent() && isForceResizableCalcMode()) {
        resetIFrame(triggerEventDesc);
      } else if (!(triggerEvent in { interval: 1 })) {
        logIgnored();
      }
    }

    var currentHeight, currentWidth;

    if (isSizeChangeDetected() || "init" === triggerEvent) {
      lockTrigger();
      resizeIFrame();
    } else {
      checkDownSizing();
    }
  }

  var sizeIFrameThrottled = throttle(sizeIFrame);

  function sendSize(triggerEvent, triggerEventDesc, customHeight, customWidth) {
    function recordTrigger() {
      if (!(triggerEvent in { reset: 1, resetPage: 1, init: 1 })) {
        log("Trigger event: " + triggerEventDesc);
      }
    }

    function isDoubleFiredEvent() {
      return triggerLocked && triggerEvent in doubleEventList;
    }

    if (!isDoubleFiredEvent()) {
      recordTrigger();
      if (triggerEvent === "init") {
        sizeIFrame(triggerEvent, triggerEventDesc, customHeight, customWidth);
      } else {
        sizeIFrameThrottled(
          triggerEvent,
          triggerEventDesc,
          customHeight,
          customWidth
        );
      }
    } else {
      log("Trigger event cancelled: " + triggerEvent);
    }
  }

  function lockTrigger() {
    if (!triggerLocked) {
      triggerLocked = true;
      log("Trigger event lock on");
    }
    clearTimeout(triggerLockedTimer);
    triggerLockedTimer = setTimeout(function () {
      triggerLocked = false;
      log("Trigger event lock off");
      log("--");
    }, eventCancelTimer);
  }

  function triggerReset(triggerEvent) {
    height = getHeight[heightCalcMode]();
    width = getWidth[widthCalcMode]();

    sendMsg(height, width, triggerEvent);
  }

  function resetIFrame(triggerEventDesc) {
    var hcm = heightCalcMode;
    heightCalcMode = heightCalcModeDefault;

    log("Reset trigger event: " + triggerEventDesc);
    lockTrigger();
    triggerReset("reset");

    heightCalcMode = hcm;
  }

  function sendMsg(height, width, triggerEvent, msg, targetOrigin) {
    function setTargetOrigin() {
      if (undefined === targetOrigin) {
        targetOrigin = targetOriginDefault;
      } else {
        log("Message targetOrigin: " + targetOrigin);
      }
    }

    function sendToParent() {
      var size = height + ":" + width,
        message =
          myID +
          ":" +
          size +
          ":" +
          triggerEvent +
          (undefined !== msg ? ":" + msg : "");

      log("Sending message to host page (" + message + ")");
      target.postMessage(msgID + message, targetOrigin);
    }

    if (true === sendPermit) {
      setTargetOrigin();
      sendToParent();
    }
  }

  function receiver(event) {
    var processRequestFromParent = {
      init: function initFromParent() {
        initMsg = event.data;
        target = event.source;

        init();
        firstRun = false;
        setTimeout(function () {
          initLock = false;
        }, eventCancelTimer);
      },

      reset: function resetFromParent() {
        if (!initLock) {
          log("Page size reset by host page");
          triggerReset("resetPage");
        } else {
          log("Page reset ignored by init");
        }
      },

      resize: function resizeFromParent() {
        sendSize("resizeParent", "Parent window requested size check");
      },

      moveToAnchor: function moveToAnchorF() {
        inPageLinks.findTarget(getData());
      },
      inPageLink: function inPageLinkF() {
        this.moveToAnchor();
      }, // Backward compatability

      pageInfo: function pageInfoFromParent() {
        var msgBody = getData();
        log("PageInfoFromParent called from parent: " + msgBody);
        onPageInfo(JSON.parse(msgBody));
        log(" --");
      },

      message: function messageFromParent() {
        var msgBody = getData();

        log("onMessage called from parent: " + msgBody);
        // eslint-disable-next-line sonarjs/no-extra-arguments
        onMessage(JSON.parse(msgBody));
        log(" --");
      },
    };

    function isMessageForUs() {
      return msgID === ("" + event.data).substr(0, msgIdLen); // ''+ Protects against non-string messages
    }

    function getMessageType() {
      return event.data.split("]")[1].split(":")[0];
    }

    function getData() {
      return event.data.substr(event.data.indexOf(":") + 1);
    }

    function isMiddleTier() {
      return (
        (!(typeof module !== "undefined" && module.exports) &&
          "iFrameResize" in window) ||
        ("jQuery" in window && "iFrameResize" in window.jQuery.prototype)
      );
    }

    function isInitMsg() {
      // Test if this message is from a child below us. This is an ugly test, however, updating
      // the message format would break backwards compatibity.
      return event.data.split(":")[2] in { true: 1, false: 1 };
    }

    function callFromParent() {
      var messageType = getMessageType();

      if (messageType in processRequestFromParent) {
        processRequestFromParent[messageType]();
      } else if (!isMiddleTier() && !isInitMsg()) {
        warn("Unexpected message (" + event.data + ")");
      }
    }

    function processMessage() {
      if (false === firstRun) {
        callFromParent();
      } else if (isInitMsg()) {
        processRequestFromParent.init();
      } else {
        log(
          'Ignored message of type "' +
            getMessageType() +
            '". Received before initialization.'
        );
      }
    }

    if (isMessageForUs()) {
      processMessage();
    }
  }

  // Normally the parent kicks things off when it detects the iFrame has loaded.
  // If this script is async-loaded, then tell parent page to retry init.
  function chkLateLoaded() {
    if ("loading" !== document.readyState) {
      window.parent.postMessage("[iFrameResizerChild]Ready", "*");
    }
  }

  addEventListener(window, "message", receiver);
  addEventListener(window, "readystatechange", chkLateLoaded);
  chkLateLoaded();
})();
window.addEventListener("load", () => {
  window.addEventListener("mouseup", (e) => {
    if (e.target.type === "submit") {
      window.parent.postMessage("submitClicked", "*");
    }
  });
});
